name: "Infrastructure"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    environment: los_for_microg_image_factory
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: 3bit/setup-hcloud@v2
      - run: hcloud version
        env:
          HCLOUD_TOKEN: ${{ secrets.TF_VAR_HCLOUD_TOKEN }}

      - uses: jberger/action-install-kubectl@master

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          # terraform_version: 0.13.0:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Format
        id: fmt
        run: terraform -chdir=infrastructure fmt -check

      - name: Terraform Init
        id: init
        run: terraform -chdir=infrastructure init

      - name: Terraform Validate
        id: validate
        run: terraform -chdir=infrastructure validate -no-color

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'pull_request'
        run: terraform -chdir=infrastructure plan -no-color -input=false -var "SSH_KEY=${{ secrets.TF_VAR_SSH_KEY }}" -var "SSH_PUB_KEY=${{ secrets.TF_VAR_SSH_PUB_KEY }}" -var "HCLOUD_TOKEN=${{ secrets.TF_VAR_HCLOUD_TOKEN }}"
        continue-on-error: true

      - name: Update Pull Request
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
            <details><summary>Show Plan</summary>
            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`
            </details>
            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform -chdir=infrastructure apply -auto-approve -input=false -var "SSH_KEY=${{ secrets.TF_VAR_SSH_KEY }}" -var "SSH_PUB_KEY=${{ secrets.TF_VAR_SSH_PUB_KEY }}" -var "HCLOUD_TOKEN=${{ secrets.TF_VAR_HCLOUD_TOKEN }}"
